# Generated by Django 4.1.7 on 2023-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(default='Al', max_length=50),
        ),
    ]
